<a href="https://colab.research.google.com/github/yazfir/Projects2021/blob/master/AlgebraLineal/InversaEnEcuacionLineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Aplicando la inversa de una matriz en un sistema de ecuaciones lineal


3x + y = 1

2x + y = 1

$$
\begin{bmatrix}
3 & 1\\
2 & 1
\end{bmatrix}
\begin{bmatrix}
x\\
y
\end{bmatrix}=
\begin{bmatrix}
1\\
1
\end{bmatrix}
$$

A*x = b


In [2]:
np.set_printoptions(suppress=True) # Ayuda a que si un número es muy cercano a cero no muestre todos los decimales, sólo cero.

In [3]:
A = np.array([[3,1],[2,1]])
A

array([[3, 1],
       [2, 1]])

In [4]:
b = np.array([[1],[1]])
b

array([[1],
       [1]])

In [6]:
inversa_A = np.linalg.inv(A)
inversa_A

array([[ 1., -1.],
       [-2.,  3.]])

In [8]:
x = inversa_A.dot(b)
x

array([[0.],
       [1.]])

Entonces:

x = 0 y = 1

In [17]:
# Comprobación
print(A.dot(x))

[[1.]
 [1.]]


-3x + y = 5

-2x + y = 3

$$
\begin{bmatrix}
-3 & 1\\
-2 & 1
\end{bmatrix}
\begin{bmatrix}
x\\
y
\end{bmatrix}=
\begin{bmatrix}
5\\
3
\end{bmatrix}
$$

A*x = b


In [10]:
A2 = np.array([[-3,1],[-2,1]])
A2

array([[-3,  1],
       [-2,  1]])

In [11]:
A2_inversa = np.linalg.inv(A2)
A2_inversa

array([[-1.,  1.],
       [-2.,  3.]])

In [15]:
b2 = np.array([[5],[3]])
b2

array([[5],
       [3]])

In [16]:
x2 = A2_inversa.dot(b2)
x2

array([[-2.],
       [-1.]])

Entonces:

x = -2 y = -1

In [18]:
#Comprobación

print(A2.dot(x2))

[[5.]
 [3.]]
