<a href="https://colab.research.google.com/github/yazfir/Projects2021/blob/master/AlgebraLineal/ProductoInternoMatrizyVector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Producto Interno - Matriz y Vector

In [2]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

Multiplicación - Matriz por Vector

$$ A = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}*
\begin{bmatrix}
2 & 3
\end{bmatrix}=
\begin{bmatrix}
2 & 6\\
6 & 12\\
10 & 18
\end{bmatrix}
$$

In [3]:
A = matriz * vector
A

array([[ 2,  6],
       [ 6, 12],
       [10, 18]])

Producto Interno - Matriz por Vector

$$ B = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}*
\begin{bmatrix}
2 & 3
\end{bmatrix}=
\begin{bmatrix}
(1*2) & + & (2*3)\\
(3*2) & + & (4*3)\\
(5*2) & + & (6*3)
\end{bmatrix}=
\begin{bmatrix}
8 & 18 & 28
\end{bmatrix}
$$

In [4]:
B = matriz.dot(vector)
B

array([ 8, 18, 28])

In [5]:
C = np.dot(matriz, vector) # Es otra manera de hacer producto interno
C

array([ 8, 18, 28])

In [7]:
D = vector.dot(matriz.T)
D

array([ 8, 18, 28])