<a href="https://colab.research.google.com/github/yazfir/Projects2021/blob/master/AlgebraLineal/PropiedadesProductoInterno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Propiedades de las Matrices
 - La multiplicación de matrices es asociativa y distributiva, no es conmutativa

* Propiedad Asociativa:
 
 A * (B * C) = (A * B) * C 

* Propiedad Distributiva:

 A * (B + C) =  (A * B) + (A * C)

* Propiedad Conmutativa:

 B * C = C * B


In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])

In [3]:
# Asociativa

ABC = A.dot(B.dot(C))
ABC

array([[ 60,  26],
       [145,  63],
       [295, 129]])

In [4]:
ABC_C = A.dot(B).dot(C)
ABC_C

array([[ 60,  26],
       [145,  63],
       [295, 129]])

In [5]:
# Distributiva

D = A.dot(B+C)
E = (A.dot(B))+(A.dot(C))

print(D)
print('\n')
print(E)

[[ 26  17]
 [ 62  41]
 [122  83]]


[[ 26  17]
 [ 62  41]
 [122  83]]


In [6]:
print(D == E)

[[ True  True]
 [ True  True]
 [ True  True]]


In [8]:
# Conmutativa. Las matrices casi nunca son conmutativas

F = B.dot(C)
G = C.dot(B)

print(F==G)
print('\n')
print(F)
print('\n')
print(G)

[[False False]
 [False False]]


[[15  7]
 [10  4]]


[[ 5 10]
 [ 8 14]]


In [11]:
# Conmutativa. Los vectores si son conmutativos.

v1 = np.array([[2],[7]])
v2 = np.array([[3],[5]])

v1_tv2 = v1.T.dot(v2)
v2_tv1 = v2.T.dot(v1)

print(v1_tv2)
print('\n')
print(v2_tv1)

[[41]]


[[41]]


In [13]:
# Ejemplo de Matrices Conmutativas-

X = np.array([[5,5],[5,5]])
Y = np.array([[5,5],[5,5]])

M = X.dot(Y)
N = Y.dot(X)

print(M==N)
print('\n')
print(M)
print('\n')
print(N)

[[ True  True]
 [ True  True]]


[[50 50]
 [50 50]]


[[50 50]
 [50 50]]
