<a href="https://colab.research.google.com/github/yazfir/Projects2021/blob/master/AlgebraLineal/SumasyBroadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Suma de Matrices (Con Dimensiones Distintas)

In [2]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

A = vector + matriz = error

$$ C = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix} +
\begin{bmatrix}
3 & 4 & 5
\end{bmatrix} = error$$

In [3]:
A = vector + matriz

A

ValueError: ignored

A = vector + matriz_t = ...

$$ A = \begin{bmatrix}
1 & 3 & 5\\
2 & 4 & 6
\end{bmatrix} +
\begin{bmatrix}
3 & 4 & 5
\end{bmatrix}=
\begin{bmatrix}
4 & 7 & 10\\
5 & 8 & 11
\end{bmatrix}
$$

In [4]:
A = matriz.T + vector
print(matriz.T)
print('\n')
print(vector)
print('\n')
print(A)

[[1 3 5]
 [2 4 6]]


[3 4 5]


[[ 4  7 10]
 [ 5  8 11]]


#Broadcasting

In [12]:
D = matriz + np.array([[42],[42],[42]])
D

array([[43, 44],
       [45, 46],
       [47, 48]])

In [11]:
C = matriz + 42  # Esto se llama broadcasting y es completar el elemento de menor dimensión hasta completar el de mayor dimensión
C

array([[43, 44],
       [45, 46],
       [47, 48]])