<a href="https://colab.research.google.com/github/yazfir/Projects2021/blob/master/AlgebraLineal/TransposicionProductoInterno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Transposición de un producto de matrices

* $(A B)^t = B^t A^t$

In [2]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])

In [3]:
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [4]:
print(B)

[[1 3]
 [2 1]]


In [5]:
AB_t = A.dot(B).T
B_tA_t = B.T.dot(A.T)

In [6]:
print(AB_t == B_tA_t)

[[ True  True  True]
 [ True  True  True]]


In [7]:
print(AB_t)

[[ 8 19 37]
 [ 9 22 46]]


In [8]:
print(B_tA_t)

[[ 8 19 37]
 [ 9 22 46]]
