<a href="https://colab.research.google.com/github/yazfir/Projects2021/blob/master/AlgebraLineal/TransposicionySuma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[27,28,29,38]],
])

In [3]:
# Transponer en Python es con el atributo: .T
# Podemos denotar estas variables con: _t

escalar_t = escalar.T #Mandara error porque una escalar no puede transponerse

AttributeError: ignored

In [4]:
vector_t = vector.T
vector_t #Para un vector queda igual ya que al no tener filas y columnas para transponerse lo deja igual

array([3, 4, 5, 6])

In [8]:
matriz_t = matriz.T
print(matriz)
print('\n')
print(matriz_t)

[[1 2]
 [3 4]
 [5 6]]


[[1 3 5]
 [2 4 6]]


In [9]:
print(matriz.shape)
print('\n')
print(matriz_t.shape)

(3, 2)


(2, 3)


In [11]:
tensor_t = tensor.T

print(tensor)
print('\n')
print(tensor_t)

[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]


[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


La transpuesta de una matriz ya transpuesta da como resultado la matriz original previo a ser transpuesta.

( $A^{t}$ )$^t$ = $A$

In [13]:
matriz_t_t = matriz_t.T

print(matriz)
print('\n')
print(matriz_t_t)

[[1 2]
 [3 4]
 [5 6]]


[[1 2]
 [3 4]
 [5 6]]


# Suma de Matrices (Mismas Dimensiones)

$$ matriz = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}$$

In [14]:
A = matriz
B = matriz_t
C = A + B # No se puede sumar porque ambas matrices deben ser de las mismas dimensiones

ValueError: ignored

$$ C = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}+
\begin{bmatrix}
6 & 5\\
4 & 3\\
2 & 1
\end{bmatrix}=
\begin{bmatrix}
7 & 7\\
7 & 7\\
7 & 7
\end{bmatrix}
$$

In [17]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[6,5],[4,3],[2,1]])
C = A+B
print(A)
print('\n+')
print(B)
print('\n=')
print(C)

[[1 2]
 [3 4]
 [5 6]]

+
[[6 5]
 [4 3]
 [2 1]]

=
[[7 7]
 [7 7]
 [7 7]]


#Matriz + Escalar

$$ D = \begin{bmatrix}
1 & 2\\
3 & 4\\
5 & 6
\end{bmatrix}+5.679=
\begin{bmatrix}
6.679 & 7.679\\
8.679 & 9.679\\
10.679 & 11.679
\end{bmatrix}
$$

In [18]:
D = matriz + escalar

D

array([[ 6.679,  7.679],
       [ 8.679,  9.679],
       [10.679, 11.679]])