<a href="https://colab.research.google.com/github/yazfir/Projects2021/blob/master/ProysDatacademy/Numpy_y_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Usando NumPy

NumPy significa "Python numérico" o "Python numérico". Es un módulo *open source* de Python que proporciona cálculos matemáticos rápidos en arreglos y matrices. Dado que los arreglos y matrices son una parte esencial del ecosistema de aprendizaje automático, NumPy se usa con otros módulos de machine learning como Scikit-learn, Pandas, Matplotlib, TensorFlow, etc.

### Jugando con numpy

**Importando el módulo**

In [1]:
import numpy as np

**Creando vectores**

In [3]:
list = [1,2,3,4,5]
vector = np.array([1,2,3,4])
vector

array([1, 2, 3, 4])

In [4]:
vector_unos = np.ones(6)
vector_unos

array([1., 1., 1., 1., 1., 1.])

In [5]:
vector_ceros = np.zeros(10)
vector_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
type(vector)

numpy.ndarray

## Usando Pandas

Pandas es una de las bibliotecas de Python más utilizadas en la ciencia de datos. Proporciona estructuras y herramientas de análisis de datos de alto rendimiento y fáciles de usar. A diferencia de la biblioteca NumPy que proporciona objetos para matrices multidimensionales, Pandas proporciona un objeto de tabla 2d en memoria llamado Dataframe. Es como una hoja de cálculo con nombres de columnas y etiquetas de filas.



###Jugando con Pandas

**Importando el módulo**

In [7]:
import pandas as pd

**Creando un DataFrame de un diccionario**

In [9]:
data = {'Nombre':['Enrique', 'Sofia', 'Carlos','Lucia'],'Edad':[24,31,29,42]}

df = pd.DataFrame(data)
df

Nombre  Edad
0  Enrique    24
1    Sofia    31
2   Carlos    29
3    Lucia    42

**Creando un DataFrame de un arreglo**

In [12]:
data = [["Enrique",24],["Sofia",31],["Carlos",29],["Lucia",42]]

df = pd.DataFrame(data, columns=['Nombres','Edad'])

df

Nombres  Edad
0  Enrique    24
1    Sofia    31
2   Carlos    29
3    Lucia    42